version: "3.7"

services:
  api-market:
    image: fgibarra/applabs-market:1.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORT=https://+:5011
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "5010:5010"
      - "5011:5011"